## ML Lab Assignment 11 

## Forward NeuralNetwork

## Arya Chakraborty [22MSD7020]

Importing Required Libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X = np.array([[6,2,3,1],[4,8,4,2],[5,6,3,3]])
X

array([[6, 2, 3, 1],
       [4, 8, 4, 2],
       [5, 6, 3, 3]])

In [4]:
X.shape

(3, 4)

In [5]:
X = X.T
X

array([[6, 4, 5],
       [2, 8, 6],
       [3, 4, 3],
       [1, 2, 3]])

In [6]:
y = np.array([[1],[1],[0]])
y = y.T
y

array([[1, 1, 0]])

Model Architecture

In [7]:
input_layer_neurons = X.shape[0]
hidden_layer_neurons = 3
output_neuron = 1

In [8]:
w_ih = np.random.uniform(size=(input_layer_neurons,hidden_layer_neurons))

w_ho = np.random.uniform(size=(hidden_layer_neurons,output_neuron))

In [9]:
w_ih.shape, w_ho.shape

((4, 3), (3, 1))

In [10]:
def sigmoid(x):
    return 1/(1+np.exp(-x))


In [11]:
hidden_layer_input = np.dot(w_ih.T, X)
hidden_layer_activations = sigmoid(hidden_layer_input)
hidden_layer_activations.shape

(3, 3)

In [12]:
output_layer_input = np.dot(w_ho.T, hidden_layer_activations)
output = sigmoid(output_layer_input)
output.shape

(1, 3)

In [13]:
output

array([[0.84675068, 0.84695771, 0.84723442]])

# Error

In [16]:
error = np.square(y-output)/2
error

array([[0.01174268, 0.01171097, 0.35890308]])